### ISSUE TITLE
blast.py looking for extra blast fields

### ISSUE THREAD

**Issue by Adamtaranto** [kdmurray91/lpipy#2]
Sample blast hit record, 12 columns:

``` bash
awk -n 1 blast_hits.tab
SNOR_00004  gi|169594556|ref|XP_001790702.1|  99.00  998  4  1  1  998  1  992  0.0  1956
```

Try to run demo.py:

```
$ ./lpipy/misc/demo.py blast_hits.tab
Taxonomy DB loaded successfully
Traceback (most recent call last):
  File "./lpipy/misc/demo.py", line 15, in <module>
    for hit in BlastFile(argv[1]):
  File "/usr/local/lib/python3.4/dist-packages/lpi-0_untagged.11.gd0f1d6a-py3.4.egg/lpi/blast.py", line 128, in __next__
    values[i] = BLAST_FIELDS[field](values[i])
IndexError: list index out of range

```

blast.py should be looking for 12 fields (same as my input):

``` python
DEFAULT_BLAST_FIELDS = [
    'qseqid',
    'sseqid',
    'pident',
    'length',
    'mismatch',
    'gapopen',
    'qstart',
    'qend',
    'sstart',
    'send',
    'evalue',
    'bitscore',
]
```

Note: Ran demo.py on a blast tab result with 18 columns, got error:

``` bash
Taxonomy DB loaded successfully
Traceback (most recent call last):
  File "./lpipy/misc/demo.py", line 15, in <module>
    for hit in BlastFile(argv[1]):
  File "/usr/local/lib/python3.4/dist-packages/lpi-0_untagged.11.gd0f1d6a-py3.4.egg/lpi/blast.py", line 129, in __next__
    return self.record(*values)
TypeError: __new__() takes 13 positional arguments but 19 were given
```

Why is it looking for 13 arguments, and not 12?

**Comment by Adamtaranto** [comment]
awk was adding two spaces instead of '\t'. fixed by using OFS.

``` bash
awk -v OFS='\t' '{ if ($12 >= 100 && $11 <=0.00001) print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12;}' mytabs/* >> master_filtered_blast_bit100_e10_5.tab
```

**Comment by kdm9** [comment]
> Why is it looking for 13 arguments, and not 12?

look at the method definition for `__init__()`. And read up on what the `self` parameter is and does, if you don't know.

**Comment by kdm9** [comment]
Oh, and for your 18 field one, give the field list as a parameter.

**Comment by Adamtaranto** [comment]
How can I get a list of all parameters?

**Comment by kdm9** [comment]
Ah, well, a little more complex than I remember. See https://github.com/kdmurray91/lpipy/blob/master/lpi/blast.py#L111 which creates the type `self.record`. So you have to give a list of length `len(fields)` from that line to the instantiation at https://github.com/kdmurray91/lpipy/blob/master/lpi/blast.py#L129.

Basically, make a list of your 18 fields and then:

``` python
fields = ['qseqid', 'sseqid', ...]
for hit in BlastFile(argv[1], fields=fields):
    do_computation_on_your(hits)
```
